### ISSUE TITLE
GRID_MAX_POINTS_X and Y modify the wrong defines

### ISSUE THREAD

**Issue by chantling** [akaJes/marlin-config#15]
Under the bedlevel menu, the first GRID_MAX_POINTS_X and GRID_MAX_POINTS_Y should be disabled unless either AUTO_BED_LEVELING_LINEAR or AUTO_BED_LEVELING_BILINEAR are enabled.  But the GRID_MAX_POINTS... seem to be always enabled.  If you enable AUTO_BED_LEVELING_UBL, the proper GRID_MAX_POINTS_X and Y for that code block are then enabled, but changing them instead alters the variables in the linear and bilinear code block instead of the UBL code block.

![grid](https://user-images.githubusercontent.com/664029/32407201-da3e573e-c15b-11e7-8abe-d71b79ffb11b.jpg)

**Comment by akaJes** [comment]
The GRID_MAX_POINTS_X is one of the not unique defines issue and i have fixed it in next version
