### ISSUE TITLE
Temperature - TEMP_SENSOR_BED (Bed Temperature) Missing Sensor 

### ISSUE THREAD

**Issue by Chazeo** [akaJes/marlin-config#17]
TEMP_SENSOR_BED has no option to select Marlin Temperature Sensor of type, 75 : 100k Generic Silicon Heat Pad with NTC 100K MGB18-104F39050L32 thermistor.

**Comment by akaJes** [comment]
it depends to source code of each version
if it exists in this line https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Configuration.h#L284
it will appears in selection box

another way is parse files like
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/thermistortables.h
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/thermistornames.h
but i have no confidence of its stable format

**Comment by akaJes** [comment]
fixed in https://github.com/akaJes/marlin-config/releases/tag/v2.8.1
