### ISSUE TITLE
Feature Request - Saving Info

### ISSUE THREAD

**Issue by nogarth** [akaJes/marlin-config#28]
just a little thing as i 3 diffrent boards and wonder if a feature can be added for exporting the Configuration.h files and others that when they are exported they go into a directory structure like

\Marlin\Marlin\.mct.bak\tags\[Board Name]\1.1.8\2018-01-05 22-29-11

that way it will be easier to load back old files and picking the correct one not the wrong one.

**Comment by akaJes** [comment]
i think for various boards is simplest to keep these in folders for each board
i  do it also for stable and dev versions

**Comment by akaJes** [comment]
it appears from 1.1.5 version
