### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by ModMike** [akaJes/marlin-config#33]
I have flagged repeatedly and ran into compilation errors:

![screen shot 2018-02-19 at 7 53 59 pm](https://user-images.githubusercontent.com/36581178/36402809-07e44ff2-15af-11e8-8fbb-647edb8affac.png)

![screen shot 2018-02-19 at 7 54 22 pm](https://user-images.githubusercontent.com/36581178/36402812-09b26d5a-15af-11e8-856b-178bfa6c5acc.png)

Can you help me out?

Thanks!

I had the first error since the beginning.

**Comment by ModMike** [comment]
I managed to reinstall and compile again but still have the first error:

![screen shot 2018-02-19 at 8 23 48 pm](https://user-images.githubusercontent.com/36581178/36403490-251c45bc-15b3-11e8-9844-667b3e4473a2.png)

**Comment by akaJes** [comment]
You colud remove the `.pioenvs` folder it will be recreated by PlatformIO
This looks like You run pio under administrative rights and than apllication under user rights

**Comment by ModMike** [comment]
I can’t seem
To find the folder, even with a search.  Do you know where it is located on a Mac?

Thanks!

MT

**Comment by akaJes** [comment]
Just deploy the firmware to new folder
or
move the visible folders to another new empty folder

**Comment by ModMike** [comment]
I fixed the issue.  There is an error in the first section of the platformio.ini, which is in the top level directory.

This si how it is:

src_dir = Marlin
env_dir = .pioenvs
lib_dir = .piolib
libdeps_dir = .piolibdeps
env_default = megaatmega2560

This is how it should be:

[platformio]
src_dir = Marlin
**build_dir** = .pioenvs
lib_dir = .piolib
libdeps_dir = .piolibdeps
env_default = megaatmega2560

Changed the bold area and the error disappears.
