### ISSUE TITLE
Latest release v2.9.1

### ISSUE THREAD

**Issue by Axoluto** [akaJes/marlin-config#40]
Im trying to run it on my Mac and it just won't open.
Application Specific Information:
dyld: launch, loading dependent libraries
This is just part of the report, does it help?
"Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/marlin-conf.app/Contents/MacOS/marlin-conf
  Reason: no suitable image found.  Did find:
	/Applications/marlin-conf.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short

Binary Images:
    0x7fff697e8000 -     0x7fff6981fa47  dyld (360.22) <C8E77F6D-CE86-3C5B-8576-2584A799B51E> /usr/lib/dyld"

**Comment by akaJes** [comment]
tryout another new files in this release
