### ISSUE TITLE
Melzi (Sanguino) atmega1284P not on list.

### ISSUE THREAD

**Issue by Wheelycool** [akaJes/marlin-config#41]
I believe this is why I keep getting "Error: The program size (69756 bytes) is greater than maximum allowed (64512 bytes)" during upload. The 1284P should have more space then 64512 bytes. The only choice on the compile list is 'sanguino_atmega644P'. What am I missing?

**Comment by Wheelycool** [comment]
![image](https://user-images.githubusercontent.com/37477533/37565379-b74ef6ac-2a7e-11e8-9a53-6a52d05feb08.png)

**Comment by akaJes** [comment]
Some microchips has not enough memory space and for compiling need to remove the most memory consuming functions or abilities or even degrade version to most suitable

**Comment by akaJes** [comment]
You could try to modify platformio.ini file by yourself for this processor according to the platformio documentation or google it

**Comment by GhostlyCrowd** [comment]
the Anet10 is sanguino_atmega1284p as you see if you compare platformio.ini files from their other source trees.  

I dont know why they keep flp-flopping the name the end user sees in their source. but it is changed back to sanguino_atmega1284p in the 1.1.x bug fix and 2.x bugfix.

**Comment by Wheelycool** [comment]
Finally got it to work, had to start with fresh code unmolested. Then update s/w, then load bugfix 2.0.X. Now compiling and uploading correctly. Thanks!
