### ISSUE TITLE
Feature Request - Add the ability to edit pins_BOARDNAME.h in the app

### ISSUE THREAD

**Issue by GhostlyCrowd** [akaJes/marlin-config#42]
Auto loading the Pins_boardname.h file associated with the board you have selected in your configuration.h would be super hand, especially for ramps users who tend to do a lot of custom pin configuration.

**Comment by akaJes** [comment]
I looked at these files and all haven't common structure
Would suggest only the plain text editor with text highlight for some kinds of files

**Comment by akaJes** [comment]
v2.10.1 has this ability in editor

**Comment by nicko954** [comment]
yea but how does it work??
