### ISSUE TITLE
Will not even begin compile

### ISSUE THREAD

**Issue by ModMike** [akaJes/marlin-config#43]
Fresh install on Windows 10.  Had to install python manually but everything else ok.  Running standard ramps 1.4 EFB, COM4, atmega 2560 clone.  Device shows up in devices as Atmega2560.  All good so far.

Copied Anet A8 config.h and config_adv. h to Marlin, changed board to 2560.  Click compile and log says "Done" immediately.

What am I doing wrong?

**Comment by akaJes** [comment]
Python is not the compiller, at start you could install PlatformIO compiller automatic with a one touch 
Than open empty folder wait a minute and drag your files in the application

**Comment by akaJes** [comment]
At start choose desired version then drop the old configuration files in the application then push dropdown of compile button for board selection and compile it

**Comment by ModMike** [comment]
I know python is not the compiler, I am just saying the install process did not work completely, I had to manually install Platform IO manually.  It would not install automatically no matter what I tried.

I don't understand what you mean by "drop the old configuration files".  Drag and drop the old files in or erase them?

**Comment by akaJes** [comment]
Drag&drop or through menu 'upload-files' button, your files will be compared and loaded over existing settings, changed options will be highligted
