### ISSUE TITLE
Choose older version from bugfix-branch?

### ISSUE THREAD

**Issue by DerDominik** [akaJes/marlin-config#53]
Hi there,

first of all. Thanks for the great tool. Works really good!
Yesterday I updated to an actual version of the bugfix-branch, which doesn't seem to work as good as before. Is there a possibility in marlin-config to choose an older version of the bugfix-branch?
If I click on "Branches" I get only the actual version?

Thanks for your help!

**Comment by akaJes** [comment]
The branch is a flow work version and in most cases is unstable or used for
tests
The tag or version is a fixed release version with numeric mark allowed for
download

Пн, 16 лип. 2018, 18:24 користувач DerDominik <notifications@github.com>
пише:
