### ISSUE TITLE
Obsolete PIO Core v3.6.0 is used (previous was 3.6.1a4)

### ISSUE THREAD

**Issue by RudyBenner** [akaJes/marlin-config#58]
Obsolete PIO Core v3.6.0 is used (previous was 3.6.1a4)

Please remove multiple PIO Cores from a system:
http://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system

The link is decidedly unhelpful.

Compiles fine with Arduino 1.8.7 Bugfix 1.1.x

**Comment by RudyBenner** [comment]
I was hoping for a resolution. Noting has changed.

**Comment by RudyBenner** [comment]
![image](https://user-images.githubusercontent.com/40361032/45611329-0aa9e080-ba2d-11e8-92af-5dccf7287510.png)
Deleted.

**Comment by RudyBenner** [comment]
I will leave it open for a while.

**Comment by akaJes** [comment]
Hi, which kind of error did you get and where?
The app detects if the command `pio` can be reached from a console and shows the installed state of PlatformIO.
Manual removing of this folder(on your image) uninstall the embedded PlatformIO of the app
 Then you can install your own version of PlatformIO manually
