### ISSUE TITLE
[bug] scrolling issues

### ISSUE THREAD

**Issue by yet-another-average-joe** [akaJes/marlin-config#64]
Hello akaJes !

When going back and forth between tabs in Marlin Configurator, it appears to have some problem with scrollbar positions.

Warning : I'm a Windows guy, I don't know about Java, and I will use a Windows vocabulary !

Problem description :

go to Gcodes tab. Scroll down to MIN_SOFTWARE_ENDSTOPS/MIN_SOFTWARE_ENDSTOPS. Then click on the hyperlink. It brings you to the matching parameter in Configuration.h. That's cool. But when selecting Gcodes tab again, position is lost.

In a windows langage, it seems that SetScrollRange is updated from one tab to another, but SetScrollPos remains the same. As a result, Gcodes tab doesn't show MIN_SOFTWARE_ENDSTOPS/MIN_SOFTWARE_ENDSTOPS no more. One have to scroll up or down to get it back.

Not a big issue, but ennoying when navigating from a tab to another using hyperlinks...

(I can upload a quick video on YouTube if you want)
(sorry for my bad english)

**Comment by akaJes** [comment]
fixed in [v2.10.5](https://github.com/akaJes/marlin-config/releases/tag/v2.10.5)
