### ISSUE TITLE
[feature request] Examples list alphabetic sorting

### ISSUE THREAD

**Issue by yet-another-average-joe** [akaJes/marlin-config#66]
Hello akaJes !

This is not an issue. But it would probably be if all printer manufacturers gave their conf files ! When opening the examples list (from the main menu), the list is not sorted. Not a big issue as examples are few, but a recursive alphabetic sort would be great (Brand/Model)

Note that I don't use this feature as I don't need it. I'm just thinking of people who have listed printers like the popular Creality CR's for example. They have to search in an un-ordered list.

(I can upload a quick video on YouTube if you want)
(sorry for my bad english)

**Comment by akaJes** [comment]
This list is just folders names

**Comment by yet-another-average-joe** [comment]
Yes indeed, but some sort would be great ! I did'nt look at the code, as I don't speek Java (C/C++ only for 30 years, and just a couple years for a living). I imagine this list is in an array, it's easy to implement a bubble sort on the array, and routines are certainly available, without having to code it by hand.

Examples have a weird behaviour on my system (Win7). When I select an example, the tabs contents is not updated, and config*.h files are not copied into Marlin folder. But the parameters are updated one by one when I click on the "reset parameter" button (the 'X'). The only way to play with examples is to copy files by hand, or use the upload feature. Tested on a real computer and a virtual machine I use as a marlin-conf server for testing purpose.

I will start tonight editiong a video with some other glitches, and I will let you informed (unreferenced video on Youtube, a link for your eyes only ; I already have some footage)

**Comment by akaJes** [comment]
I can it sort at least
Choosing some from the Examples is just shows the Differences to your base configuration
The `reset` command do coping of files from examples or from git version

**Comment by yet-another-average-joe** [comment]
On my system (win7), it does not copy example files. Will do a video soon (within 12-14 hours) in order to show you the weird behaviour with examples...

(yes, I still run win7 because one app I need does not run under 8 or 10)

**Comment by akaJes** [comment]
fixed in [v2.10.5](https://github.com/akaJes/marlin-config/releases/tag/v2.10.5)
