### ISSUE TITLE
[bug ?] optionnal files _Bootscreen.h, _Statusscreen.h not copied in worling folder

### ISSUE THREAD

**Issue by yet-another-average-joe** [akaJes/marlin-config#67]
Hello akaJes !

While testing marlin conf and example conf selection, it appears that when selecting an example printer configuration, thefollowing files are not copied to the Marlin directory :

_Boortsceen.h
_Statusscreen.h

Therefore, they will not be included in the compilation, and will not appear on the printer LCD screen. 

Note that I do not own a listed printer. I tested compilation and had a look to log screen. I didn't see any of these two files in the .o file list.

(I can upload a quick video on YouTube if you want)
(sorry for my bad english)

**Comment by akaJes** [comment]
fixed in [v2.10.5](https://github.com/akaJes/marlin-config/releases/tag/v2.10.5)
