### ISSUE TITLE
[feature request] Search field in menu bar

### ISSUE THREAD

**Issue by yet-another-average-joe** [akaJes/marlin-config#70]
Hello akaJes !

The search field collapses as soon as the mouse comes out of the edit field. Why not let it expanded as long as it has the focus ? Not remaining opened, the search field appears somewhat "jumpy" and not intuitive...

Also, is there some shortkey like search prev/search next ? I didn't find... Classical F3/shift F3 would be great ! It would make navigation much easier !

A workaround is to open marlin-conf in a browser with localhost:port, and use the browser search function.

Or maybe running marlin-conf as a classical webpage, the localhost:port way,  in a full browser insteed of a browser control ? (it seems to me that it runs this way, but not sure). Maybe, it could be more convenient, particularly when clicking on external links like Marlin issues, opening a tab in the same window.

(I can upload a quick video on YouTube if you want)
(sorry for my bad english)

**Comment by akaJes** [comment]
The electron hasn't classic search like in browser it emulated
fixed in [v2.10.5](https://github.com/akaJes/marlin-config/releases/tag/v2.10.5)
