### ISSUE TITLE
[bug] CONFIGURATION_ADV_H_VERSION not updated by marlin-conf

### ISSUE THREAD

**Issue by yet-another-average-joe** [akaJes/marlin-config#71]
Hello !

A bug :

CONFIGURATION_ADV_H_VERSION not updated after conf files upgrade (drag/drop or upload)

as a result, the updated project will not compile.

Should be :

form Marlin 1.1.0 RC8 to Marlin 1.1.6 : 010101
Marlin 1.1.7 : 010107
Marlin 1.1.8 : 010107
Marlin 1.1.9 : 010109

No problem with Configuration.h, CONFIGURATION_H_VERSION is updated

This problem does not occurs with mct (command line utility)

**Comment by akaJes** [comment]
fixed in [v2.10.5](https://github.com/akaJes/marlin-config/releases/tag/v2.10.5)
