### ISSUE TITLE
2.10.6 is broken !

### ISSUE THREAD

**Issue by yet-another-average-joe** [akaJes/marlin-config#78]
Hello,

I was very excited about 2.10.6, but :

- it takes 4 minutes to load (tested several times with Win7 and Win10) : blank marlin-conf window, blank browser page (using localhost:3000 or whatever). No disk activity, no network activity, no processor activity. Same 4 minutes when switching to another Marlin version, and also when hitting Reset.

- examples menu item won't open examples list

- no more Editor (the new one seems to be gorgeous !)

tested with Win7 and Win10, tested after uninstalling previous version and also installing over previous version, Win7 and Win10.

I had to revert to 2.10.5, as I am testing marlin-conf vs mct about firmware upgrades (some differences found)

**Comment by GhostlyCrowd** [comment]
Can confirm same issues

**Comment by RudyBenner** [comment]
Was running older version. Tried to update. No go.

**Comment by RudyBenner** [comment]
Ok, version 2.10.3 works. I am back to where I was. The newer versions go off into the ionosphere.

**Comment by RudyBenner** [comment]
Tried to update to 2.10.6. No luck at all. Tried older versions. 2.10.3 works.

**Comment by akaJes** [comment]
Fixed in 2.10.7
