### ISSUE TITLE
Custom boards?

### ISSUE THREAD

**Issue by gcormier** [akaJes/marlin-config#8]
What is the best way to add a custom board definition?

**Comment by akaJes** [comment]
there is ability only for listed boards(supported with firmware) and also for the example configurations
the best way to support a custom board is to suggest it for marlin firmware community

**Comment by gcormier** [comment]
It would be useful to be able to customize the pins somehow in this tool. The pins often change between various machines as a matter of customization (ie. bed sensor types using different pins). The Marlin FW doesn't want header files for every variation out there, but we still need a way to set these values. A potential future feature?

**Comment by ravini-mephisto** [comment]
If you can follow the PlatformIO documentation (http://docs.platformio.org/en/latest/projectconf.html)
you will be able to customize the platformio.ini file that comes with Marlin.  
For example, take a look at the custom platformio.ini made my the Skynet3D project for Anet printer users: https://github.com/SkyNet3D/Marlin/blob/SkyNet3D-Devel/platformio.ini

**Comment by akaJes** [comment]
@gcormier i looked at files with pin assignments - these are so various and have no common standart 
this idea is interesting but at this moment i have no plan how to implement it
