### ISSUE TITLE
Issue: It's Too Good :)

### ISSUE THREAD

**Issue by riverratdc** [akaJes/marlin-config#9]
It's a truly elegant & powerful application. Bravo, akaJes!

Like others, I await the ability donate to the cause.

Thanks for all of your great efforts.

**Comment by akaJes** [comment]
Thank you for using
I'm trying to create paypal account from neighbor country, but don't know how long time it takes

**Comment by akaJes** [comment]
[![](http://www.pngall.com/wp-content/uploads/2016/05/PayPal-Donate-Button-PNG.png)](https://www.paypal.me/AKruk508)
